name: neodata
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - scipy
  - matplotlib
  - netcdf4
  - wradlib
  - cartopy
  - arm_pyart
  - xarray
  - pip
  - pip:
      - nexradaws
      - grpcio
      - grpcio-tools
      - gunicorn
      - netCDF4
      - requests