apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadata-service-deploy
spec:
  selector:
    matchLabels:
      app: metadata-service
  replicas: 3
  template:
    metadata:
      labels:
        app: metadata-service

    spec:
      containers:
      - name: metadata-service
        imagePullPolicy: Always
        image: neoairavataproject/metadata-service:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 52000
      restartPolicy: Always