apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-service-deploy
spec:
  selector:
    matchLabels:
      app: registry-service
  replicas: 2
  template:
    metadata:
      labels:
        app: registry-service

    spec:
      containers:
      - name: registry-service
        imagePullPolicy: Always
        image: neoairavataproject/registry-service:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 41000
      restartPolicy: Always